server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
multipart:
  max-file-size: 10MB
  max-request-size: 10MB
